In [13]:

a, b, c, d, e = map(int, input("请输入5个数字：").split())
num = [a, b, c, d, e]

num_max = []

def my_max(x,y):
    return x if x>y else y
 
while num:
    m = num[0]
    for i in num[1:]:
        m = my_max(m,i)
    num_max.append(m)
    num.remove(m)
    
a, b, c, d, e = num_max
print(num)
print(num_max)
print(a)

[]
[45, 8, 6, 1, 1]
45


In [17]:
digits = [1, 2, 3, 4]
ans = []
for a in digits:
    for b in digits:
        for c in digits:
            if a != b and a != c and b != c:
                ans.append(100*a + 10*b + c)

print(len(ans), sorted(ans))  # 24, [...]

24 [123, 124, 132, 134, 142, 143, 213, 214, 231, 234, 241, 243, 312, 314, 321, 324, 341, 342, 412, 413, 421, 423, 431, 432]


In [18]:
import itertools
digits = [1, 2, 3, 4]
ans = [100*a + 10*b + c for a, b, c in itertools.permutations(digits, 3)]
print(len(ans), sorted(ans))  # 24, [...]

24 [123, 124, 132, 134, 142, 143, 213, 214, 231, 234, 241, 243, 312, 314, 321, 324, 341, 342, 412, 413, 421, 423, 431, 432]


In [23]:
import numpy as np
from PIL import Image
a = np.array(Image.open("1.png"))
print(a)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
